### ISSUE TITLE
Enable CORS for localhost

### ISSUE THREAD

**Issue by vslala** [VSProductions/ticket-tracker#1]
Currently not able to call the backend service from frontend due to CORs. Need to enable CORs in the backend so that the APIs can be consumed by the frontend.

@INNOMIGHT

**Comment by INNOMIGHT** [comment]
Sure, on my way to do the same.

**Comment by vslala** [comment]
Cross-site communication enabled after adding `corsheader`.
Commit that fixed it: [a267589c46a5c175ed6f30a0942b4c85d211b0fd](https://github.com/VSProductions/ticket-tracker/commit/a267589c46a5c175ed6f30a0942b4c85d211b0fd)
